services:
  - type: web
    name: angular-app
    env: node
    buildCommand: npm install && npm run build --prod
    startCommand: serve -s dist/gyanpath-frontend -l 3000
    envVars:
      - key: NODE_ENV
        value: production
    plan: free  
    timeout: 900