version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  eureka-server:
    container_name: eureka-server
    image: eureka-server:latest
    build:
      context: ./server-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
  
  apigateway:
    container_name: api-gateway
    image: apigateway:latest
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    restart: always

  security:
    container_name: security
    image: security:latest
    build: 
      context: ./security
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${Security_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERENAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EUREKA_SERVER: ${EUREKA_SERVER}
      SERVER_PORT: ${SECURITY_SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      TOKEN_EXPIRATION_TIME: ${TOKEN_EXPIRATION_TIME}
      REFRESH_TOKEN_EXPIRATION_TIME: ${REFRESH_TOKEN_EXPIRATION_TIME}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}

      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_REDIRECT_URI: ${GITHUB_REDIRECT_URI}

      FRONTEND_URL: ${FRONTEND_URL}

  quiz:
    container_name: quiz
    image: quiz:latest
    build: 
      context: ./quiz
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${Quiz_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERENAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EUREKA_SERVER: ${EUREKA_SERVER}
      SERVER_PORT: ${Quiz_SERVER_PORT}

  question:
    container_name: question
    image: question:latest
    build:
      context: ./question
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${Question_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERENAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EUREKA_SERVER: ${EUREKA_SERVER}
      SERVER_PORT: ${Question_SERVER_PORT}

volumes:
  mysql_data:
