spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://SECURITY
          predicates:
            - Path= /oauth2/**, /login/**, /logout/**, /api/auth/**
        - id: quiz-service
          uri: lb://QUIZ
          predicates:
            - Path=/api/quiz/**
        - id: question-service
          uri: lb://QUESTION
          predicates:
            - Path=/api/question/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200/'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Content-Type
              - Response-Type
              - Authorization
            allowCredentials: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  registerWithEureka: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
